from typing import List, Dict, Any

AWS_SERVICES: List[Dict[str, Any]] = [
    # ── Compute ──────────────────────────────────────────────────────────
    {
        "id": "ec2",
        "name": "Amazon EC2",
        "category": "Compute",
        "description": "Resizable virtual machines in the cloud. Provides full control over OS, networking, and storage with hundreds of instance types optimized for different workloads.",
        "key_features": [
            "Hundreds of instance types (CPU, GPU, memory-optimized)",
            "Auto Scaling and Elastic Load Balancing",
            "Spot, On-Demand, Reserved, and Savings Plans pricing",
            "Placement groups and Dedicated Hosts",
            "Hibernate and stop-start lifecycle",
        ],
        "use_cases": ["Web & app servers", "HPC workloads", "Dev/test environments", "Machine learning inference"],
        "pricing_notes": "Charged per second (min 60 s) for most Linux instances. t3.micro costs ~$0.0104/hr in us-east-1.",
        "pricing_model": "Per-second (on-demand) / reserved / spot",
        "free_tier": "750 hrs/month of t2.micro or t3.micro for 12 months",
        "docs_url": "https://docs.aws.amazon.com/ec2/",
    },
    {
        "id": "lambda",
        "name": "AWS Lambda",
        "category": "Compute",
        "description": "Serverless compute that runs code in response to events without provisioning or managing servers. Scales automatically from zero to thousands of concurrent executions.",
        "key_features": [
            "Supports Python, Node.js, Java, Go, .NET, Ruby, and custom runtimes",
            "Event-driven triggers (S3, DynamoDB, API Gateway, SNS, etc.)",
            "Up to 15-minute execution timeout",
            "Built-in fault tolerance across multiple AZs",
            "Lambda Layers for shared code",
        ],
        "use_cases": ["API backends", "Real-time file processing", "Scheduled tasks", "Stream processing"],
        "pricing_notes": "$0.20 per 1M requests + $0.0000166667 per GB-second of compute.",
        "pricing_model": "Per request + per GB-second",
        "free_tier": "1M requests and 400,000 GB-seconds per month (always free)",
        "docs_url": "https://docs.aws.amazon.com/lambda/",
    },
    {
        "id": "ecs",
        "name": "Amazon ECS",
        "category": "Compute",
        "description": "Fully managed container orchestration service supporting Docker containers. Integrates natively with AWS networking, IAM, and observability services.",
        "key_features": [
            "Fargate (serverless) and EC2 launch types",
            "Deep integration with ALB, NLB, and CloudMap",
            "Task definitions with CPU/memory limits",
            "Service auto-scaling and rolling deployments",
            "Native AWS IAM roles per task",
        ],
        "use_cases": ["Microservices", "Batch processing", "Long-running apps", "CI/CD pipelines"],
        "pricing_notes": "No additional charge for ECS itself. You pay for EC2 instances or Fargate vCPU/memory time.",
        "pricing_model": "Pay for underlying compute (EC2 or Fargate)",
        "free_tier": "No charge for ECS control plane",
        "docs_url": "https://docs.aws.amazon.com/ecs/",
    },
    {
        "id": "eks",
        "name": "Amazon EKS",
        "category": "Compute",
        "description": "Managed Kubernetes service that removes the need to operate your own Kubernetes control plane. Runs upstream, certified Kubernetes.",
        "key_features": [
            "Managed control plane with automatic upgrades",
            "Supports EC2, Fargate, and EKS Anywhere",
            "Native VPC networking via AWS VPC CNI",
            "OIDC-based IAM for service accounts",
            "EKS Add-ons for common cluster components",
        ],
        "use_cases": ["Container orchestration", "Multi-tenant platforms", "Hybrid deployments", "Kubernetes-native apps"],
        "pricing_notes": "$0.10 per cluster per hour for the control plane (~$72/month). Worker node EC2/Fargate costs are separate.",
        "pricing_model": "$0.10/hr per cluster + compute",
        "free_tier": "No free tier for the control plane",
        "docs_url": "https://docs.aws.amazon.com/eks/",
    },
    # ── Storage ───────────────────────────────────────────────────────────
    {
        "id": "s3",
        "name": "Amazon S3",
        "category": "Storage",
        "description": "Industry-leading object storage with 99.999999999% (11 nines) durability. Stores and retrieves any amount of data from anywhere on the web.",
        "key_features": [
            "Storage classes: Standard, Intelligent-Tiering, Glacier, Deep Archive",
            "Versioning, replication (cross-region & same-region)",
            "S3 Select and S3 Glacier Select for in-place querying",
            "Lifecycle policies for automatic tiering",
            "Event notifications to Lambda, SQS, SNS",
        ],
        "use_cases": ["Static website hosting", "Data lake storage", "Backup & archive", "Media distribution"],
        "pricing_notes": "Standard storage ~$0.023/GB/month. GET requests $0.0004/1,000. Data transfer OUT from $0.09/GB.",
        "pricing_model": "Per GB stored + per request + data transfer",
        "free_tier": "5 GB Standard storage, 20,000 GETs, 2,000 PUTs per month for 12 months",
        "docs_url": "https://docs.aws.amazon.com/s3/",
    },
    {
        "id": "ebs",
        "name": "Amazon EBS",
        "category": "Storage",
        "description": "High-performance block storage designed for use with Amazon EC2. Volumes persist independently from EC2 instance lifecycles.",
        "key_features": [
            "Volume types: gp3, gp2, io2, io1, st1, sc1",
            "Up to 64,000 IOPS and 1,000 MB/s throughput (io2)",
            "Snapshots stored in S3 for backup and duplication",
            "Encryption at rest and in transit with KMS",
            "Multi-attach for io1/io2 (read-write from multiple instances)",
        ],
        "use_cases": ["Database storage", "Boot volumes", "High-IOPS workloads", "Transactional applications"],
        "pricing_notes": "gp3 ~$0.08/GB/month. io2 ~$0.125/GB/month + $0.065 per provisioned IOPS above 32,000.",
        "pricing_model": "Per GB provisioned per month + provisioned IOPS",
        "free_tier": "30 GB of EBS storage (gp2/gp3/magnetic) for 12 months",
        "docs_url": "https://docs.aws.amazon.com/ebs/",
    },
    {
        "id": "efs",
        "name": "Amazon EFS",
        "category": "Storage",
        "description": "Fully managed, elastic NFS file system for Linux workloads. Scales on demand to petabytes without disrupting applications.",
        "key_features": [
            "Shared access from thousands of EC2, ECS, and Lambda instances",
            "Performance modes: General Purpose and Max I/O",
            "Throughput modes: Bursting, Provisioned, and Elastic",
            "EFS Lifecycle Management for IA storage class",
            "Encryption at rest and in transit",
        ],
        "use_cases": ["Content management", "Web serving", "Home directories", "Data analytics"],
        "pricing_notes": "Standard storage ~$0.30/GB/month. Infrequent Access ~$0.025/GB/month + $0.01/GB accessed.",
        "pricing_model": "Per GB stored per month",
        "free_tier": "5 GB of EFS Standard storage for 12 months",
        "docs_url": "https://docs.aws.amazon.com/efs/",
    },
    # ── Database ──────────────────────────────────────────────────────────
    {
        "id": "rds",
        "name": "Amazon RDS",
        "category": "Database",
        "description": "Managed relational database service supporting MySQL, PostgreSQL, MariaDB, Oracle, SQL Server, and Amazon Aurora. Automates backups, patching, and failover.",
        "key_features": [
            "Multi-AZ deployments for high availability",
            "Read replicas for horizontal read scaling",
            "Automated backups with point-in-time recovery",
            "Performance Insights and Enhanced Monitoring",
            "Storage Auto Scaling",
        ],
        "use_cases": ["OLTP applications", "E-commerce", "Content management systems", "SaaS backends"],
        "pricing_notes": "db.t3.micro (MySQL) ~$0.017/hr. Storage ~$0.115/GB/month. I/O-optimized instances available.",
        "pricing_model": "Per instance-hour + storage + I/O",
        "free_tier": "750 hrs/month db.t2.micro/db.t3.micro + 20 GB storage for 12 months",
        "docs_url": "https://docs.aws.amazon.com/rds/",
    },
    {
        "id": "dynamodb",
        "name": "Amazon DynamoDB",
        "category": "Database",
        "description": "Fully managed, serverless NoSQL key-value and document database that delivers single-digit millisecond performance at any scale.",
        "key_features": [
            "On-demand and provisioned capacity modes",
            "Global Tables for multi-region, active-active replication",
            "DynamoDB Streams for change data capture",
            "DAX (in-memory cache) for microsecond reads",
            "ACID transactions across multiple items/tables",
        ],
        "use_cases": ["Session management", "Shopping carts", "Gaming leaderboards", "IoT data ingestion"],
        "pricing_notes": "On-demand: $1.25/million write RCUs, $0.25/million read RCUs. Storage $0.25/GB/month.",
        "pricing_model": "Per request (on-demand) or provisioned RCU/WCU + storage",
        "free_tier": "25 GB storage + 25 WCU + 25 RCU (always free)",
        "docs_url": "https://docs.aws.amazon.com/dynamodb/",
    },
    {
        "id": "elasticache",
        "name": "Amazon ElastiCache",
        "category": "Database",
        "description": "Fully managed in-memory caching service supporting Redis OSS and Memcached. Sub-millisecond latency at internet scale.",
        "key_features": [
            "Redis: replication, clustering, Lua scripting, pub/sub, sorted sets",
            "Memcached: multi-threaded, simple horizontal scaling",
            "Serverless option (ElastiCache Serverless) auto-scales capacity",
            "Encryption in transit and at rest",
            "Redis AUTH and RBAC for access control",
        ],
        "use_cases": ["Database caching", "Session storage", "Real-time leaderboards", "Message queuing"],
        "pricing_notes": "cache.t3.micro ~$0.017/hr. Serverless: $0.00034/ECPUs + $0.0001/GB-hour storage.",
        "pricing_model": "Per node-hour (provisioned) or per ECPU (serverless)",
        "free_tier": "750 hrs/month of cache.t2.micro/t3.micro for 12 months",
        "docs_url": "https://docs.aws.amazon.com/elasticache/",
    },
    # ── Networking ────────────────────────────────────────────────────────
    {
        "id": "cloudfront",
        "name": "Amazon CloudFront",
        "category": "Networking",
        "description": "Global content delivery network (CDN) with 450+ points of presence. Delivers websites, APIs, video, and other assets with low latency and high transfer speeds.",
        "key_features": [
            "450+ edge locations and regional edge caches",
            "Lambda@Edge and CloudFront Functions for edge compute",
            "Origin Shield to reduce origin load",
            "Field-Level Encryption for sensitive data",
            "Real-time logs and built-in DDoS protection (Shield Standard)",
        ],
        "use_cases": ["Static asset delivery", "Live & on-demand video", "API acceleration", "Software distribution"],
        "pricing_notes": "Data transfer OUT from $0.0085–$0.17/GB depending on region. 10M HTTP requests ~$0.01.",
        "pricing_model": "Per GB transferred + per HTTP request",
        "free_tier": "1 TB data transfer + 10M HTTP/HTTPS requests per month (always free)",
        "docs_url": "https://docs.aws.amazon.com/cloudfront/",
    },
    {
        "id": "route53",
        "name": "Amazon Route 53",
        "category": "Networking",
        "description": "Highly available and scalable cloud DNS web service. Offers domain registration, DNS routing, and health checking.",
        "key_features": [
            "Routing policies: Simple, Weighted, Latency, Failover, Geolocation, Multivalue",
            "Health checks and DNS failover",
            "Traffic Flow visual editor for complex routing",
            "Private hosted zones within a VPC",
            "DNSSEC signing support",
        ],
        "use_cases": ["Domain registration", "Global load balancing", "Blue/green DNS failover", "Private DNS"],
        "pricing_notes": "$0.50/hosted zone/month (first 25 zones). $0.40/million standard queries.",
        "pricing_model": "Per hosted zone per month + per query",
        "free_tier": "No free tier",
        "docs_url": "https://docs.aws.amazon.com/route53/",
    },
    {
        "id": "api-gateway",
        "name": "Amazon API Gateway",
        "category": "Networking",
        "description": "Fully managed service to create, publish, maintain, monitor, and secure REST, HTTP, and WebSocket APIs at any scale.",
        "key_features": [
            "REST API, HTTP API, and WebSocket API types",
            "Built-in authentication via Cognito, Lambda authorizers, or IAM",
            "Request/response transformation and validation",
            "Usage plans and API keys for throttling",
            "Caching with configurable TTL",
        ],
        "use_cases": ["Serverless API frontends", "Microservice routing", "Real-time apps (WebSocket)", "Backend-for-Frontend"],
        "pricing_notes": "HTTP API: $1/million requests. REST API: $3.50/million requests. WebSocket: $1/million messages.",
        "pricing_model": "Per million API calls + data transfer",
        "free_tier": "1M REST API calls and 1M HTTP API calls per month for 12 months",
        "docs_url": "https://docs.aws.amazon.com/apigateway/",
    },
    # ── AI & ML ───────────────────────────────────────────────────────────
    {
        "id": "sagemaker",
        "name": "Amazon SageMaker",
        "category": "AI & ML",
        "description": "End-to-end machine learning platform to build, train, and deploy ML models at scale. Includes integrated Jupyter notebooks, AutoML, and MLOps tools.",
        "key_features": [
            "SageMaker Studio IDE with managed notebooks",
            "Autopilot for automated model creation",
            "Managed training with distributed computing support",
            "Model deployment to real-time, batch, and async endpoints",
            "Feature Store, Model Registry, and Pipelines for MLOps",
        ],
        "use_cases": ["Custom model training", "Computer vision", "NLP", "Fraud detection"],
        "pricing_notes": "ml.t3.medium notebook instance ~$0.046/hr. Training and inference instances priced separately.",
        "pricing_model": "Per instance-hour (varies by component)",
        "free_tier": "250 hrs/month ml.t3.medium for Studio + 50 hrs training + 125 hrs inference for 2 months",
        "docs_url": "https://docs.aws.amazon.com/sagemaker/",
    },
    {
        "id": "bedrock",
        "name": "Amazon Bedrock",
        "category": "AI & ML",
        "description": "Fully managed service providing access to high-performing foundation models (FMs) from Amazon and leading AI companies via a single API.",
        "key_features": [
            "Foundation models: Claude, Llama, Titan, Mistral, Stable Diffusion, and more",
            "Knowledge Bases for RAG (Retrieval-Augmented Generation)",
            "Agents to automate multi-step tasks",
            "Fine-tuning and continued pre-training",
            "Model evaluation and guardrails",
        ],
        "use_cases": ["Chatbots", "Text summarization", "Code generation", "Image generation"],
        "pricing_notes": "On-demand pricing per 1,000 input/output tokens varies by model. E.g. Claude 3 Haiku ~$0.00025/1K input tokens.",
        "pricing_model": "Per 1,000 tokens (text) or per image generated",
        "free_tier": "No free tier",
        "docs_url": "https://docs.aws.amazon.com/bedrock/",
    },
    {
        "id": "rekognition",
        "name": "Amazon Rekognition",
        "category": "AI & ML",
        "description": "Cloud-based computer vision service that identifies objects, people, text, scenes, and activities in images and videos using deep learning.",
        "key_features": [
            "Object and scene detection",
            "Facial analysis, recognition, and comparison",
            "Text-in-image detection (OCR)",
            "Content moderation for unsafe imagery",
            "Custom Labels for domain-specific models",
        ],
        "use_cases": ["Identity verification", "Content moderation", "Media analysis", "Workplace safety"],
        "pricing_notes": "Image analysis: first 1M images/month free tier then $0.001/image. Video $0.10/min.",
        "pricing_model": "Per image / per minute of video",
        "free_tier": "5,000 image analyses + 1,000 face metadata stores per month for 12 months",
        "docs_url": "https://docs.aws.amazon.com/rekognition/",
    },
    # ── Security ──────────────────────────────────────────────────────────
    {
        "id": "iam",
        "name": "AWS IAM",
        "category": "Security",
        "description": "Identity and Access Management — securely control access to AWS services and resources for users, groups, roles, and workloads.",
        "key_features": [
            "Fine-grained JSON policies (identity- and resource-based)",
            "IAM Roles for EC2, Lambda, ECS, and cross-account access",
            "MFA enforcement and password policies",
            "IAM Access Analyzer for unused permissions",
            "Service Control Policies (SCPs) via AWS Organizations",
        ],
        "use_cases": ["Least-privilege access control", "Cross-account roles", "Federated SSO", "Workload identity"],
        "pricing_notes": "IAM is free. IAM Identity Center (SSO) is free for built-in identity store.",
        "pricing_model": "Free",
        "free_tier": "Always free",
        "docs_url": "https://docs.aws.amazon.com/iam/",
    },
    {
        "id": "kms",
        "name": "AWS KMS",
        "category": "Security",
        "description": "Managed service to create and control cryptographic keys used to encrypt data across AWS services and applications.",
        "key_features": [
            "Symmetric and asymmetric (RSA, ECC) key types",
            "Automatic annual key rotation",
            "CloudTrail logging for every key usage",
            "Multi-Region Keys for cross-region encrypted data",
            "Key policies and grants for fine-grained access",
        ],
        "use_cases": ["S3 and EBS encryption", "RDS and DynamoDB encryption", "Code signing", "Secrets management"],
        "pricing_notes": "$1/customer-managed key/month. $0.03 per 10,000 API requests.",
        "pricing_model": "Per key per month + per API request",
        "free_tier": "No free tier for CMKs; AWS-managed keys are free",
        "docs_url": "https://docs.aws.amazon.com/kms/",
    },
    # ── Analytics ─────────────────────────────────────────────────────────
    {
        "id": "athena",
        "name": "Amazon Athena",
        "category": "Analytics",
        "description": "Serverless, interactive query service to analyze data in Amazon S3 using standard SQL. No infrastructure to manage.",
        "key_features": [
            "Standard SQL (Presto/Trino engine) on S3 data",
            "Supports CSV, JSON, Parquet, ORC, Avro formats",
            "Federated queries to RDS, DynamoDB, and other sources",
            "Integration with AWS Glue Data Catalog",
            "Workgroups for cost control and query isolation",
        ],
        "use_cases": ["Ad-hoc data exploration", "Log analysis", "Data lake querying", "Cost and billing analysis"],
        "pricing_notes": "$5 per TB of data scanned. Use columnar formats (Parquet/ORC) and partitioning to reduce scans.",
        "pricing_model": "Per TB of data scanned",
        "free_tier": "No free tier (but S3 free tier applies to storage)",
        "docs_url": "https://docs.aws.amazon.com/athena/",
    },
    {
        "id": "kinesis",
        "name": "Amazon Kinesis",
        "category": "Analytics",
        "description": "Suite of services for real-time streaming data ingestion, processing, and analysis at any scale.",
        "key_features": [
            "Kinesis Data Streams: real-time data ingestion (shards)",
            "Kinesis Data Firehose: load streams to S3, Redshift, OpenSearch",
            "Kinesis Data Analytics: SQL or Apache Flink on streams",
            "Data retention up to 365 days",
            "Enhanced fan-out for parallel consumers",
        ],
        "use_cases": ["Real-time dashboards", "Clickstream analytics", "IoT telemetry", "Log aggregation"],
        "pricing_notes": "Data Streams: $0.015/shard/hr + $0.014/million PUT records. Firehose: $0.029/GB ingested.",
        "pricing_model": "Per shard-hour + per record / per GB",
        "free_tier": "No free tier",
        "docs_url": "https://docs.aws.amazon.com/kinesis/",
    },
]

CATEGORIES = sorted(set(s["category"] for s in AWS_SERVICES))
